default_events:
  - issues
  - pull_request
  - pull_request_review
  default_permissions:
  issues: write
  metadata: read
  pull_requests: write
  description: A Put Request Review Bot
  public: true
